export const ImagesActionTypes = {
	SET_IMAGES: 'SET_IMAGES',
	DELETE_IMAGE: 'DELETE_IMAGE',
	FETCH_IMAGES: 'FETCH_IMAGES',
	REMOVE_IMAGE: 'REMOVE_IMAGE',
	SAVE_IMAGE: 'SAVE_IMAGE',
	UPLOAD_IMAGE: 'UPLOAD_IMAGE',
	CREATE_IMAGE_INSTANCE_IN_DATABASE: 'CREATE_IMAGE_INSTANCE_IN_DATABASE',
}
