export const AuthActionTypes = {
	SET_CURRENT_USER: 'SET_CURRENT_USER',
	SIGN_IN_WITH_EMAIL: 'SIGN_IN_WITH_EMAIL',
	SIGN_IN_WITH_GOOGLE: 'SIGN_IN_WITH_GOOGLE',
	SIGN_UP_WITH_EMAIL_AND_PASSWORD: 'SIGN_UP_WITH_EMAIL_AND_PASSWORD',
	SIGN_OUT: 'SIGN_OUT',
	SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
}
